version: "3.9"

services:
  rag-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: rag_app

    ports:
      - "8000:8000"

    env_file:
      - ../.env   # NOT pushed to GitHub

    volumes:
      - rag_data:/app/backend/data   # persistence

    restart: always

volumes:
  rag_data: